import type { ResearchDataset } from "@/types/research";

export const mockResearchDataset: ResearchDataset = {
  themes: [
    {
      id: "theme-kr-policy",
      slug: "korea-policy-reset",
      name: "Korea Policy Reset",
      description:
        "Fiscal support, supplementary budget talk, and domestic policy shifts affecting Korea risk assets.",
      category: "Policy",
      priority: "High",
      color: "#9f6b2c",
    },
    {
      id: "theme-rates-path",
      slug: "rates-path",
      name: "Rates Path",
      description:
        "Central bank communication, inflation prints, and duration positioning across KR and US curves.",
      category: "Macro",
      priority: "Critical",
      color: "#264b6d",
    },
    {
      id: "theme-ai-supply",
      slug: "ai-supply-chain",
      name: "AI Supply Chain",
      description:
        "Capex, compute bottlenecks, and demand read-through across semiconductors and hyperscalers.",
      category: "Sector",
      priority: "Critical",
      color: "#2e6a64",
    },
    {
      id: "theme-energy-tightness",
      slug: "energy-tightness",
      name: "Energy Tightness",
      description:
        "Oil supply discipline, shipping friction, and second-order inflation impact.",
      category: "Cross-Asset",
      priority: "Medium",
      color: "#875d34",
    },
    {
      id: "theme-fx-defense",
      slug: "fx-defense",
      name: "FX Defense",
      description:
        "KRW stabilization measures, dollar funding pressure, and intervention-sensitive trades.",
      category: "Risk",
      priority: "High",
      color: "#4e5f95",
    },
    {
      id: "theme-semi-cycle",
      slug: "semiconductor-cycle",
      name: "Semiconductor Cycle",
      description:
        "Memory pricing, export momentum, and semiconductor inventory turns.",
      category: "Sector",
      priority: "Critical",
      color: "#355c7d",
    },
    {
      id: "theme-china-demand",
      slug: "china-demand-reboot",
      name: "China Demand Reboot",
      description:
        "China policy easing and the knock-on effect for Korean exporters and materials.",
      category: "Macro",
      priority: "Medium",
      color: "#8c4f42",
    },
    {
      id: "theme-safe-havens",
      slug: "safe-haven-flow",
      name: "Safe Haven Flow",
      description:
        "Treasuries, gold, and defensive positioning when macro conviction softens.",
      category: "Cross-Asset",
      priority: "High",
      color: "#657a54",
    },
    {
      id: "theme-defense-capex",
      slug: "defense-capex",
      name: "Defense Capex",
      description:
        "Defense spending cycles and export upside for Korean aerospace and systems suppliers.",
      category: "Sector",
      priority: "Medium",
      color: "#4f4c78",
    },
    {
      id: "theme-risk-appetite",
      slug: "risk-appetite",
      name: "Risk Appetite",
      description:
        "Cross-asset positioning, leverage conditions, and tactical sentiment swings.",
      category: "Risk",
      priority: "Medium",
      color: "#6c5b43",
    },
  ],
  tickers: [
    {
      id: "ticker-005930-ks",
      symbol: "005930.KS",
      name: "Samsung Electronics",
      exchange: "KRX",
      region: "KR",
      assetClass: "Equities",
      note: "Core Korea semiconductor bellwether and export sensitivity proxy.",
    },
    {
      id: "ticker-000660-ks",
      symbol: "000660.KS",
      name: "SK Hynix",
      exchange: "KRX",
      region: "KR",
      assetClass: "Equities",
      note: "High-beta memory and HBM exposure for AI and cyclical turns.",
    },
    {
      id: "ticker-nvda",
      symbol: "NVDA",
      name: "NVIDIA",
      exchange: "NASDAQ",
      region: "US",
      assetClass: "Equities",
      note: "Lead AI compute beneficiary and sentiment anchor for growth risk.",
    },
    {
      id: "ticker-msft",
      symbol: "MSFT",
      name: "Microsoft",
      exchange: "NASDAQ",
      region: "US",
      assetClass: "Equities",
      note: "Hyperscaler capex signal source and AI monetization proxy.",
    },
    {
      id: "ticker-qqq",
      symbol: "QQQ",
      name: "Invesco QQQ Trust",
      exchange: "NASDAQ",
      region: "US",
      assetClass: "ETF",
      note: "Growth and duration-sensitive positioning vehicle.",
    },
    {
      id: "ticker-tlt",
      symbol: "TLT",
      name: "iShares 20+ Year Treasury Bond ETF",
      exchange: "NASDAQ",
      region: "US",
      assetClass: "ETF",
      note: "Clean duration expression for rates-path calls.",
    },
    {
      id: "ticker-gld",
      symbol: "GLD",
      name: "SPDR Gold Shares",
      exchange: "NYSE Arca",
      region: "GLOBAL",
      assetClass: "ETF",
      note: "Liquid safe-haven and real-yield hedge expression.",
    },
    {
      id: "ticker-xle",
      symbol: "XLE",
      name: "Energy Select Sector SPDR",
      exchange: "NYSE Arca",
      region: "US",
      assetClass: "ETF",
      note: "Broad energy beta to crude supply headlines.",
    },
    {
      id: "ticker-kb",
      symbol: "105560.KS",
      name: "KB Financial",
      exchange: "KRX",
      region: "KR",
      assetClass: "Equities",
      note: "Korean bank proxy for curve steepening and domestic policy support.",
    },
    {
      id: "ticker-hanwha",
      symbol: "012450.KS",
      name: "Hanwha Aerospace",
      exchange: "KRX",
      region: "KR",
      assetClass: "Equities",
      note: "Defense export beneficiary tied to multi-year procurement pipelines.",
    },
    {
      id: "ticker-btc",
      symbol: "BTC-USD",
      name: "Bitcoin",
      exchange: "Crypto",
      region: "GLOBAL",
      assetClass: "Crypto",
      note: "Sentiment and liquidity-sensitive macro risk barometer.",
    },
    {
      id: "ticker-kodex200",
      symbol: "069500.KS",
      name: "KODEX 200",
      exchange: "KRX",
      region: "KR",
      assetClass: "ETF",
      note: "Broad Korea beta expression for local policy and export momentum.",
    },
    {
      id: "ticker-posco",
      symbol: "005490.KS",
      name: "POSCO Holdings",
      exchange: "KRX",
      region: "KR",
      assetClass: "Equities",
      note: "Materials exposure to China demand and industrial reflation.",
    },
  ],
  newsItems: [
    {
      id: "news-001",
      title: "Korea fiscal support talk revives domestic beta into the morning scan",
      summary:
        "Local brokers flagged renewed supplementary budget discussion as enough to rotate flows back into domestic cyclicals and broad Korea beta.",
      sourceName: "Yonhap",
      sourceUrl: "https://en.yna.co.kr/",
      publishedAt: "2026-03-11T08:42:00+09:00",
      scanSlot: "09",
      region: "KR",
      affectedAssetClasses: ["Equities", "ETF"],
      relatedThemeIds: ["theme-kr-policy", "theme-risk-appetite"],
      relatedTickerIds: ["ticker-kodex200", "ticker-kb"],
      marketInterpretation:
        "Policy chatter is not a hard catalyst yet, but it improves the floor for domestic beta while foreign flow stays selective.",
      directionalView: "Bullish",
      actionIdea:
        "Lean into Korea beta on weakness rather than chase. Prefer liquid vehicles and banks over smaller cyclicals.",
      followUpStatus: "Pending",
      followUpNote:
        "Need confirmation from budget headlines and foreign flow before upgrading conviction.",
      importance: "High",
      createdAt: "2026-03-11T08:55:00+09:00",
      updatedAt: "2026-03-11T08:55:00+09:00",
    },
    {
      id: "news-002",
      title: "US core CPI cooldown eases duration pressure ahead of the New York open",
      summary:
        "A softer-than-feared inflation read triggered a relief move in long duration while keeping growth leadership intact for now.",
      sourceName: "Reuters",
      sourceUrl: "https://www.reuters.com/markets/us/",
      publishedAt: "2026-03-11T09:06:00+09:00",
      scanSlot: "09",
      region: "US",
      affectedAssetClasses: ["Rates", "ETF", "Equities"],
      relatedThemeIds: ["theme-rates-path", "theme-safe-havens"],
      relatedTickerIds: ["ticker-tlt", "ticker-qqq"],
      marketInterpretation:
        "The print extends tactical room for duration, but one cool release alone does not secure a full easing cycle.",
      directionalView: "Bullish",
      actionIdea:
        "Maintain tactical TLT watchlist bias and keep QQQ positions, but avoid assuming a straight-line rally.",
      followUpStatus: "Pending",
      followUpNote:
        "Watch whether Fed speakers validate the market move within 24 hours.",
      importance: "Critical",
      createdAt: "2026-03-11T09:10:00+09:00",
      updatedAt: "2026-03-11T09:10:00+09:00",
    },
    {
      id: "news-003",
      title: "Oil steadies as OPEC discipline offsets anxiety around China demand",
      summary:
        "Crude held its ground despite softer China talk after delegates signaled supply discipline would remain firm into next quarter.",
      sourceName: "Bloomberg",
      sourceUrl: "https://www.bloomberg.com/markets",
      publishedAt: "2026-03-11T09:24:00+09:00",
      scanSlot: "09",
      region: "GLOBAL",
      affectedAssetClasses: ["Commodities", "ETF", "Equities"],
      relatedThemeIds: [
        "theme-energy-tightness",
        "theme-china-demand",
        "theme-risk-appetite",
      ],
      relatedTickerIds: ["ticker-xle"],
      marketInterpretation:
        "Energy remains supported by supply management more than growth optimism, which argues for tactical not structural conviction.",
      directionalView: "Mixed",
      actionIdea:
        "Keep energy as an inflation hedge sleeve, but trim expectations for a broad commodity breakout.",
      followUpStatus: "Pending",
      followUpNote: "Need to see whether physical spreads keep improving.",
      importance: "Medium",
      createdAt: "2026-03-11T09:32:00+09:00",
      updatedAt: "2026-03-11T09:32:00+09:00",
    },
    {
      id: "news-004",
      title: "Bank of Korea signals readiness to lean against one-way KRW moves",
      summary:
        "Officials emphasized smoothing rather than defending a specific level, but the messaging was enough to temper intraday dollar momentum.",
      sourceName: "The Korea Herald",
      sourceUrl: "https://www.koreaherald.com/",
      publishedAt: "2026-03-11T12:41:00+09:00",
      scanSlot: "13",
      region: "KR",
      affectedAssetClasses: ["FX", "Equities"],
      relatedThemeIds: ["theme-fx-defense", "theme-rates-path"],
      relatedTickerIds: ["ticker-kb", "ticker-kodex200"],
      marketInterpretation:
        "The signal reduces tail risk in the won, but it is more a volatility suppressor than a durable trend change by itself.",
      directionalView: "Neutral",
      actionIdea:
        "Avoid chasing exporters on FX alone. Prefer domestically linked names if KRW stabilizes without hurting rates.",
      followUpStatus: "Pending",
      followUpNote:
        "Monitor whether spot closes below recent intervention-sensitive ranges.",
      importance: "High",
      createdAt: "2026-03-11T12:50:00+09:00",
      updatedAt: "2026-03-11T12:50:00+09:00",
    },
    {
      id: "news-005",
      title: "Hyperscaler capex checks keep AI supply chain leadership intact",
      summary:
        "Channel checks suggested no meaningful pause in AI infrastructure spend, reinforcing leadership for high-end chips and memory suppliers.",
      sourceName: "The Information",
      sourceUrl: "https://www.theinformation.com/",
      publishedAt: "2026-03-11T12:57:00+09:00",
      scanSlot: "13",
      region: "US",
      affectedAssetClasses: ["Equities"],
      relatedThemeIds: ["theme-ai-supply", "theme-semi-cycle"],
      relatedTickerIds: [
        "ticker-nvda",
        "ticker-msft",
        "ticker-000660-ks",
        "ticker-005930-ks",
      ],
      marketInterpretation:
        "Leadership is still earnings-backed, but the market is increasingly paying up for visibility rather than acceleration.",
      directionalView: "Bullish",
      actionIdea:
        "Stay long core AI winners, but rotate adds into supply-chain names where revisions can still surprise positively.",
      followUpStatus: "Pending",
      followUpNote:
        "Need next round of supplier guidance to judge whether pricing power is still broadening.",
      importance: "Critical",
      createdAt: "2026-03-11T13:04:00+09:00",
      updatedAt: "2026-03-11T13:04:00+09:00",
    },
    {
      id: "news-006",
      title: "China property easing lifts Korean materials exporters in the afternoon",
      summary:
        "Incremental policy support from Chinese local governments boosted steel and battery-material names with China demand exposure.",
      sourceName: "Nikkei Asia",
      sourceUrl: "https://asia.nikkei.com/",
      publishedAt: "2026-03-11T13:18:00+09:00",
      scanSlot: "13",
      region: "GLOBAL",
      affectedAssetClasses: ["Equities"],
      relatedThemeIds: ["theme-china-demand", "theme-kr-policy"],
      relatedTickerIds: ["ticker-posco"],
      marketInterpretation:
        "The move reads as a tradable reflation pulse rather than a clean medium-term turn in China domestic demand.",
      directionalView: "Mixed",
      actionIdea:
        "Treat reflation-sensitive Korea materials as tactical trades unless policy support broadens materially.",
      followUpStatus: "Pending",
      followUpNote:
        "Need broader property sales and credit data before upgrading to bullish.",
      importance: "Medium",
      createdAt: "2026-03-11T13:22:00+09:00",
      updatedAt: "2026-03-11T13:22:00+09:00",
    },
    {
      id: "news-007",
      title: "Korea early export data surprises on semiconductors and memory pricing",
      summary:
        "Preliminary shipment data pointed to stronger semiconductor exports, with memory pricing commentary helping high-beta chip names into the close.",
      sourceName: "Maeil Business",
      sourceUrl: "https://www.mk.co.kr/en/",
      publishedAt: "2026-03-11T17:51:00+09:00",
      scanSlot: "18",
      region: "KR",
      affectedAssetClasses: ["Equities"],
      relatedThemeIds: ["theme-semi-cycle", "theme-ai-supply"],
      relatedTickerIds: ["ticker-005930-ks", "ticker-000660-ks"],
      marketInterpretation:
        "This reinforces the current earnings revision path for Korea semis and makes pullbacks easier to buy.",
      directionalView: "Bullish",
      actionIdea:
        "Favor SK Hynix on momentum and Samsung on catch-up quality. Use export data as confirmation rather than the first signal.",
      followUpStatus: "Pending",
      followUpNote: "Need confirmation from spot memory pricing in the weekly check.",
      importance: "Critical",
      createdAt: "2026-03-11T18:02:00+09:00",
      updatedAt: "2026-03-11T18:02:00+09:00",
    },
    {
      id: "news-008",
      title: "Fed speakers push back on early cuts and cool the duration rally",
      summary:
        "Post-CPI commentary reminded markets that one benign data point is not enough, briefly reversing part of the earlier move in Treasuries.",
      sourceName: "Wall Street Journal",
      sourceUrl: "https://www.wsj.com/news/markets",
      publishedAt: "2026-03-11T18:14:00+09:00",
      scanSlot: "18",
      region: "US",
      affectedAssetClasses: ["Rates", "Equities", "ETF"],
      relatedThemeIds: ["theme-rates-path", "theme-safe-havens"],
      relatedTickerIds: ["ticker-tlt", "ticker-qqq"],
      marketInterpretation:
        "The market is still trading the data more than the speakers, but policy pushback caps the speed of any duration follow-through.",
      directionalView: "Mixed",
      actionIdea:
        "Keep duration on the watchlist, but wait for a better entry rather than adding aggressively into the first relief bid.",
      followUpStatus: "Pending",
      followUpNote:
        "Review the overnight close to see whether bonds hold the post-speaker retracement.",
      importance: "High",
      createdAt: "2026-03-11T18:20:00+09:00",
      updatedAt: "2026-03-11T18:20:00+09:00",
    },
    {
      id: "news-009",
      title: "Bitcoin ETF inflows cool, but leverage metrics remain constructive",
      summary:
        "Flows moderated after a strong stretch, though derivatives positioning still looked orderly enough to avoid a near-term unwind signal.",
      sourceName: "CoinDesk",
      sourceUrl: "https://www.coindesk.com/markets/",
      publishedAt: "2026-03-11T18:39:00+09:00",
      scanSlot: "18",
      region: "GLOBAL",
      affectedAssetClasses: ["Crypto"],
      relatedThemeIds: ["theme-risk-appetite"],
      relatedTickerIds: ["ticker-btc"],
      marketInterpretation:
        "The setup argues for consolidation rather than immediate breakdown, but upside likely needs fresh spot flow.",
      directionalView: "Mixed",
      actionIdea:
        "Avoid sizing new crypto risk off stale momentum. Wait for flow re-acceleration or cleaner funding reset.",
      followUpStatus: "Pending",
      followUpNote: "Track ETF net flow trend over the next two sessions.",
      importance: "Medium",
      createdAt: "2026-03-11T18:45:00+09:00",
      updatedAt: "2026-03-11T18:45:00+09:00",
    },
    {
      id: "news-010",
      title: "Europe defense orders broaden supplier read-through for Korea names",
      summary:
        "Incremental order commentary in Europe strengthened the case for a longer defense upcycle reaching Korean aerospace suppliers.",
      sourceName: "Financial Times",
      sourceUrl: "https://www.ft.com/world",
      publishedAt: "2026-03-11T21:27:00+09:00",
      scanSlot: "22",
      region: "GLOBAL",
      affectedAssetClasses: ["Equities"],
      relatedThemeIds: ["theme-defense-capex", "theme-risk-appetite"],
      relatedTickerIds: ["ticker-hanwha"],
      marketInterpretation:
        "The theme is maturing from tactical order headlines into a multi-quarter backlog story.",
      directionalView: "Bullish",
      actionIdea:
        "Keep Hanwha Aerospace on the watchlist as a pullback buyer. Favor backlog visibility over valuation complaints.",
      followUpStatus: "Pending",
      followUpNote:
        "Need contract timing clarity and margin assumptions to move from watchlist to active buy.",
      importance: "High",
      createdAt: "2026-03-11T21:40:00+09:00",
      updatedAt: "2026-03-11T21:40:00+09:00",
    },
    {
      id: "news-011",
      title: "Gold holds firm as real yields retreat from recent highs",
      summary:
        "Bullion stayed resilient even as the dollar remained firm, with real-yield easing offsetting the FX headwind.",
      sourceName: "MarketWatch",
      sourceUrl: "https://www.marketwatch.com/investing/",
      publishedAt: "2026-03-11T21:48:00+09:00",
      scanSlot: "22",
      region: "GLOBAL",
      affectedAssetClasses: ["Commodities", "ETF", "Rates"],
      relatedThemeIds: ["theme-safe-havens", "theme-rates-path"],
      relatedTickerIds: ["ticker-gld", "ticker-tlt"],
      marketInterpretation:
        "Gold is behaving like a useful hedge again, especially if growth leadership starts to narrow.",
      directionalView: "Bullish",
      actionIdea:
        "Keep GLD in the watchlist hedge bucket, particularly if real yields continue to soften without a growth scare.",
      followUpStatus: "Pending",
      followUpNote:
        "Confirm with a second session of follow-through before sizing defensively.",
      importance: "Medium",
      createdAt: "2026-03-11T21:58:00+09:00",
      updatedAt: "2026-03-11T21:58:00+09:00",
    },
    {
      id: "news-012",
      title: "Renewed Treasury auction demand sparks a tactical rebound in duration",
      summary:
        "Stronger-than-feared auction demand helped long-end Treasuries stabilize after a bruising selloff, reviving a tactical bounce setup.",
      sourceName: "Reuters",
      sourceUrl: "https://www.reuters.com/markets/rates-bonds/",
      publishedAt: "2026-03-10T18:25:00+09:00",
      scanSlot: "18",
      region: "US",
      affectedAssetClasses: ["Rates", "ETF"],
      relatedThemeIds: ["theme-rates-path", "theme-safe-havens"],
      relatedTickerIds: ["ticker-tlt"],
      marketInterpretation:
        "Positioning was washed enough for a rebound, though the call was framed as tactical rather than the start of a trend.",
      directionalView: "Bullish",
      actionIdea:
        "Use TLT for a short-horizon mean-reversion trade and keep expectations modest unless inflation cools too.",
      followUpStatus: "Correct",
      followUpNote:
        "The next session held gains and validated the tactical bounce, but the move stalled once Fed speakers turned firmer.",
      importance: "High",
      createdAt: "2026-03-10T18:32:00+09:00",
      updatedAt: "2026-03-11T18:25:00+09:00",
    },
    {
      id: "news-013",
      title: "KRW stabilization talk briefly caps exporters before dip-buyers step back",
      summary:
        "Export-heavy Korea names lost momentum when stabilization headlines hit the tape, but the pullback faded quickly once spot pressure eased.",
      sourceName: "Bloomberg",
      sourceUrl: "https://www.bloomberg.com/asia",
      publishedAt: "2026-03-10T13:10:00+09:00",
      scanSlot: "13",
      region: "KR",
      affectedAssetClasses: ["FX", "Equities"],
      relatedThemeIds: ["theme-fx-defense", "theme-semi-cycle"],
      relatedTickerIds: ["ticker-005930-ks", "ticker-kodex200"],
      marketInterpretation:
        "The FX headline was not strong enough to break the export trend, suggesting local buyers still trust the earnings backdrop.",
      directionalView: "Mixed",
      actionIdea:
        "Do not fade semiconductor leadership purely on KRW stabilization headlines unless the currency move becomes sustained.",
      followUpStatus: "Correct",
      followUpNote:
        "Semis recovered intraday and closed firm, validating the view that FX noise was not enough to reset the trend.",
      importance: "Medium",
      createdAt: "2026-03-10T13:18:00+09:00",
      updatedAt: "2026-03-11T09:00:00+09:00",
    },
    {
      id: "news-014",
      title: "Energy equities catch a bid on shipping disruption headlines",
      summary:
        "Supply-chain disruption headlines pushed crude-sensitive equities higher, though broad commodity confirmation stayed incomplete.",
      sourceName: "CNBC",
      sourceUrl: "https://www.cnbc.com/energy/",
      publishedAt: "2026-03-10T09:05:00+09:00",
      scanSlot: "09",
      region: "GLOBAL",
      affectedAssetClasses: ["Equities", "Commodities", "ETF"],
      relatedThemeIds: ["theme-energy-tightness", "theme-risk-appetite"],
      relatedTickerIds: ["ticker-xle"],
      marketInterpretation:
        "The initial move had headline energy but lacked broad cross-commodity confirmation, reducing confidence after the first day.",
      directionalView: "Bullish",
      actionIdea:
        "Take tactical energy upside, but be ready to tighten the trade if crude fails to confirm within 24 hours.",
      followUpStatus: "Mixed",
      followUpNote:
        "Energy held part of the gain, but the broader move stalled once supply headlines stopped escalating.",
      importance: "Medium",
      createdAt: "2026-03-10T09:12:00+09:00",
      updatedAt: "2026-03-11T08:30:00+09:00",
    },
    {
      id: "news-015",
      title: "AI supply chain multiples stretch after a two-session melt-up",
      summary:
        "The desk flagged valuation stretch in AI leaders after a sharp momentum burst and argued for waiting on better add levels.",
      sourceName: "Barron's",
      sourceUrl: "https://www.barrons.com/market-data",
      publishedAt: "2026-03-09T22:03:00+09:00",
      scanSlot: "22",
      region: "US",
      affectedAssetClasses: ["Equities", "ETF"],
      relatedThemeIds: ["theme-ai-supply", "theme-semi-cycle", "theme-risk-appetite"],
      relatedTickerIds: ["ticker-nvda", "ticker-qqq", "ticker-000660-ks"],
      marketInterpretation:
        "The core trend remained healthy, but chasing after back-to-back expansion sessions looked poor on risk-reward.",
      directionalView: "Mixed",
      actionIdea:
        "Keep positions, but wait for digestion before increasing exposure. Favor second-order suppliers over crowded leaders.",
      followUpStatus: "Correct",
      followUpNote:
        "Leadership paused over the next session and offered better add levels without breaking the broader trend.",
      importance: "High",
      createdAt: "2026-03-09T22:12:00+09:00",
      updatedAt: "2026-03-10T18:50:00+09:00",
    },
    {
      id: "news-016",
      title: "Korea banks outperform on steeper-curve expectations into the weekly close",
      summary:
        "Domestic banks outperformed after dealers started pricing a stickier nominal backdrop and better NIM support.",
      sourceName: "Seoul Economic Daily",
      sourceUrl: "https://www.sedaily.com/",
      publishedAt: "2026-03-09T13:31:00+09:00",
      scanSlot: "13",
      region: "KR",
      affectedAssetClasses: ["Equities"],
      relatedThemeIds: ["theme-rates-path", "theme-kr-policy"],
      relatedTickerIds: ["ticker-kb"],
      marketInterpretation:
        "The move improved the case for banks as a portfolio stabilizer within a risk-on Korea book.",
      directionalView: "Bullish",
      actionIdea:
        "Use banks as quality domestic beta rather than a pure rates trade. KB remains the cleanest liquid expression.",
      followUpStatus: "Correct",
      followUpNote:
        "Banks kept relative strength while cyclicals rotated, supporting the idea of them as stabilizing domestic exposure.",
      importance: "Medium",
      createdAt: "2026-03-09T13:36:00+09:00",
      updatedAt: "2026-03-10T09:00:00+09:00",
    },
  ],
  followUps: [
    {
      id: "follow-001",
      newsItemId: "news-012",
      status: "Correct",
      resolvedAt: "2026-03-11T17:58:00+09:00",
      outcomeSummary:
        "Duration bounced as expected immediately after the auction, then gave back some gains once Fed commentary hardened.",
      resultNote:
        "Good tactical call. The trade worked, but the note correctly framed it as a short-horizon rebound rather than a durable shift.",
      marketImpact: "TLT held its first-day rebound and closed above the prior session low.",
    },
    {
      id: "follow-002",
      newsItemId: "news-013",
      status: "Correct",
      resolvedAt: "2026-03-11T09:02:00+09:00",
      outcomeSummary:
        "Semiconductor leaders recovered after the currency headline faded and resumed leadership by the next session.",
      resultNote:
        "The call avoided an unnecessary fade of exporters and kept focus on the earnings trend instead of FX noise.",
      marketImpact: "Samsung and KODEX 200 both erased the intraday dip within one session.",
    },
    {
      id: "follow-003",
      newsItemId: "news-014",
      status: "Mixed",
      resolvedAt: "2026-03-11T08:15:00+09:00",
      outcomeSummary:
        "Energy names held part of the move, but the broader breakout never fully materialized.",
      resultNote:
        "The headline mattered, but the follow-through was too shallow for a high-conviction continuation call.",
      marketImpact: "XLE stayed firm, while crude itself lost momentum into Asia hours.",
    },
    {
      id: "follow-004",
      newsItemId: "news-015",
      status: "Correct",
      resolvedAt: "2026-03-10T17:46:00+09:00",
      outcomeSummary:
        "AI leaders paused and offered better re-entry levels before trend support reappeared.",
      resultNote:
        "Waiting for digestion improved entry quality without forcing a bearish view on the underlying theme.",
      marketImpact: "NVDA and QQQ both chopped sideways after the melt-up before stabilizing.",
    },
    {
      id: "follow-005",
      newsItemId: "news-016",
      status: "Correct",
      resolvedAt: "2026-03-10T09:10:00+09:00",
      outcomeSummary:
        "Korea banks kept relative strength and cushioned the portfolio while higher-beta names rotated.",
      resultNote:
        "This worked as a balance call inside the Korea book rather than an outright sector chase.",
      marketImpact: "KB Financial outperformed the KOSPI in the next session.",
    },
    {
      id: "follow-006",
      newsItemId: "news-005",
      status: "Pending",
      resolvedAt: null,
      outcomeSummary:
        "Need the next supplier guide and order backlog commentary to judge whether the capex thesis is broadening.",
      resultNote:
        "Monitor memory names and hyperscalers over the next two weekly updates.",
      marketImpact: "Awaiting outcome.",
    },
    {
      id: "follow-007",
      newsItemId: "news-010",
      status: "Pending",
      resolvedAt: null,
      outcomeSummary:
        "The backlog story looks promising, but the next step is checking order timing and margin conversion.",
      resultNote:
        "Keep on watchlist and revisit after the next management commentary.",
      marketImpact: "Awaiting outcome.",
    },
    {
      id: "follow-008",
      newsItemId: "news-011",
      status: "Pending",
      resolvedAt: null,
      outcomeSummary:
        "Need a second session of follow-through to validate gold as a live hedge rather than a one-day relief move.",
      resultNote:
        "Compare gold strength against the next real-yield move and equity breadth.",
      marketImpact: "Awaiting outcome.",
    },
  ],
  portfolioItems: [
    {
      id: "portfolio-001",
      symbol: "000660.KS",
      assetName: "SK Hynix",
      assetType: "Stock",
      region: "KR",
      isHolding: true,
      isWatchlist: false,
      weight: 16.2,
      averageCost: 173000,
      memo: "Core AI memory winner. Prefer to add on export-data-confirmed pullbacks.",
      priority: "Critical",
    },
    {
      id: "portfolio-002",
      symbol: "NVDA",
      assetName: "NVIDIA",
      assetType: "Stock",
      region: "US",
      isHolding: true,
      isWatchlist: false,
      weight: 11.5,
      averageCost: 742,
      memo: "Long-term compounder, but avoid oversizing after vertical momentum bursts.",
      priority: "High",
    },
    {
      id: "portfolio-003",
      symbol: "QQQ",
      assetName: "Invesco QQQ Trust",
      assetType: "ETF",
      region: "US",
      isHolding: true,
      isWatchlist: false,
      weight: 18,
      averageCost: 503,
      memo: "Growth beta anchor. Watch rates sensitivity closely.",
      priority: "Medium",
    },
    {
      id: "portfolio-004",
      symbol: "TLT",
      assetName: "iShares 20+ Year Treasury Bond ETF",
      assetType: "ETF",
      region: "US",
      isHolding: false,
      isWatchlist: true,
      memo: "Waiting for a cleaner duration entry after Fed pushback.",
      priority: "High",
    },
    {
      id: "portfolio-005",
      symbol: "GLD",
      assetName: "SPDR Gold Shares",
      assetType: "ETF",
      region: "GLOBAL",
      isHolding: false,
      isWatchlist: true,
      memo: "Potential macro hedge if growth breadth narrows.",
      priority: "Medium",
    },
    {
      id: "portfolio-006",
      symbol: "012450.KS",
      assetName: "Hanwha Aerospace",
      assetType: "Stock",
      region: "KR",
      isHolding: false,
      isWatchlist: true,
      memo: "High-conviction watchlist name for defense-capex theme.",
      priority: "High",
    },
  ],
  preferences: {
    id: "preferences-001",
    timezone: "Asia/Seoul",
    preferredSort: "importance",
    favoriteSlots: ["09", "18"],
    defaultRegions: ["KR", "US"],
    interestThemeIds: [
      "theme-ai-supply",
      "theme-semi-cycle",
      "theme-rates-path",
      "theme-fx-defense",
    ],
    compactMode: false,
  },
};

export function cloneMockDataset() {
  return JSON.parse(JSON.stringify(mockResearchDataset)) as ResearchDataset;
}
